In [1]:
import time
import numpy as np

In [3]:
np.zeros((0), dtype=np.float32)

array([], dtype=float32)

In [3]:
def organize_observations_linear(flat_observations, num_tags):
    features_per_ray = num_tags + 2
    # obs_arr = np.array(flat_observations)
    selected = flat_observations[:,features_per_ray - 1::features_per_ray]
    return selected


In [39]:
a = np.array([[0,0,0,0],[-1,-1,-1,-1],[-2,-2,-2,-2], [-3,-3,-3,-3], [-4,-4,-4,-4]])
b = np.array([1,2,3,4,5])

c = np.array([[0,0,0,0], [-3,-3,-3,-3], [-4,-4,-4,-4]])
d = np.array([1,4,5])

In [2]:
for i in range(0, 100, 25):
    print(i)

0
25
50
75


In [40]:
mask = np.isin(b, d)
mask

array([ True, False, False,  True,  True])

In [45]:
sum(mask)

3

In [44]:
np.nan

nan

In [42]:
a[mask,:] = 0

In [43]:
a

array([[ 0,  0,  0,  0],
       [-1, -1, -1, -1],
       [-2, -2, -2, -2],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [ ]:
obs = np.array(
                [
                    [1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4],
                    [5,6,7,8,5,6,7,8,5,6,7,8,5,6,7,8]
                ]
            )


In [28]:
b = organize_observations_linear(obs, 2)

In [29]:
a = obs.reshape((2,4,-1))[:,:,1:].reshape(2,-1)

In [31]:
np.concatenate([a,b], axis=1)

array([[2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 4, 4, 4, 4],
       [6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8, 8, 8, 8, 8]])

In [34]:
obs[:,0]

array([1, 5])

In [15]:
obs.reshape(-1, 3 + 1)[:,1:]

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8]])

In [1]:
import torch

a = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,2,3,4,5])

torch.cat((a,b))

tensor([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [2]:
for i in range(100):
    print(get_initial_action(9))

[0.17919181 0.13619642]
[0.36015217 0.05497246]
[0.78171926 0.18833663]
[0.72847415 0.18810799]
[0.57425537 0.28011194]
[0.74502886 0.39472764]
[0.83812131 0.37437668]
[0.63289798 0.50784771]
[0.7413706 0.3038973]
[0.68277967 0.50342226]
[0.80272041 0.3870878 ]
[0.81992587 0.49978784]
[0.944385   0.42803916]
[0.88826373 0.56106047]
[0.74639719 0.33370392]
[0.81252019 0.30911789]
[0.71129193 0.41585334]
[0.63465662 0.20935412]
[0.56722639 0.34506766]
[0.66523818 0.05627894]
[ 0.67483785 -0.29739548]
[ 0.55269862 -0.42091634]
[ 0.72004023 -0.47655608]
[ 0.73293846 -0.67782278]
[ 0.46305212 -0.53149356]
[ 0.54195847 -0.63013768]
[ 0.56514428 -0.82022399]
[ 0.57544428 -0.84384146]
[ 0.53206036 -1.        ]
[ 0.24273554 -0.92293601]
[ 0.23256858 -0.91656979]
[ 0.37811664 -0.853751  ]
[ 0.24253563 -0.84752744]
[ 0.31680931 -1.        ]
[ 0.09318077 -0.75819849]
[-0.00878368 -0.67286323]
[-0.07843724 -0.47242136]
[-0.34261152 -0.38814719]
[-0.39858264 -0.35686445]
[-0.55741279 -0.09745145]
[-

In [3]:
a = np.concatenate([[1,2,3,4,5]]*10)

In [4]:
a

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5])

In [5]:
a = 1
alpha = 0.9
for i in range(100):
    if abs(a - -1) < 0.05:
        break
    print(i, a)
    a = a*alpha + -1*(1 - alpha)

0 1
1 0.8
2 0.6200000000000001
3 0.4580000000000002
4 0.3122000000000002
5 0.1809800000000002
6 0.06288200000000022
7 -0.043406199999999784
8 -0.1390655799999998
9 -0.2251590219999998
10 -0.3026431197999998
11 -0.3723788078199998
12 -0.43514092703799984
13 -0.49162683433419985
14 -0.5424641509007799
15 -0.5882177358107019
16 -0.6293959622296317
17 -0.6664563660066685
18 -0.6998107294060016
19 -0.7298296564654014
20 -0.7568466908188612
21 -0.7811620217369751
22 -0.8030458195632776
23 -0.8227412376069498
24 -0.8404671138462548
25 -0.8564204024616293
26 -0.8707783622154663
27 -0.8837005259939197
28 -0.8953304733945278
29 -0.905797426055075
30 -0.9152176834495674
31 -0.9236959151046107
32 -0.9313263235941496
33 -0.9381936912347346
34 -0.9443743221112612
35 -0.949936889900135


In [6]:
a = -0.5
alpha = 0.8
for i in range(100):
    if abs(a - -1) < 0.05:
        break
    print(i, a)
    a = a*alpha + -1*(1 - alpha)

0 -0.5
1 -0.6
2 -0.6799999999999999
3 -0.7439999999999999
4 -0.7951999999999999
5 -0.8361599999999999
6 -0.8689279999999999
7 -0.8951423999999999
8 -0.9161139199999999
9 -0.932891136
10 -0.9463129088


In [7]:
a.reshape(-1, 5)[:,1:].flatten()

AttributeError: 'float' object has no attribute 'reshape'

In [ ]:
import numpy as np

for i in range(100):
    print(np.random.normal(0, 0.2))

-0.034748155456724585
-0.35439161183800666
0.12888871824008372
0.3350918162498966
0.6160287816822363
-0.5097410471314051
0.17363081544410075
0.2632696489355774
0.05108727222118037
0.044474807667638686
-0.09524187380629025
0.01086896849709349
0.024606433155040863
0.1283619914537079
0.0795076933010897
0.02320919864082628
-0.01713011623816139
-0.20342362110968218
-0.05278813024978527
0.0637844964040075
-0.35706042443476144
-0.01991315522235614
-0.2480100434346767
0.05930417751264903
-0.211790534108279
0.2782755789340449
-0.04431727213858308
-0.12793846070894707
-0.11605646635978242
0.09189189054473025
-0.05811697243456901
0.2746903206563427
0.5428440383610988
0.2362280101677425
-0.16231403974179318
0.08935916010914906
-0.1373252444586271
-0.1055095031757109
0.1381897817574847
-0.08064101317633121
0.04826654065992375
0.1069370965547663
0.005163319643300211
-0.10091915296288934
-0.16608750440645623
-0.11626806924565486
0.13283415880415234
0.22064747639228557
-0.13666471148236237
0.127511688

In [ ]:
[1,2,3,4,5,6,7,8,9,10,11,12,13][::3]

[1, 4, 7, 10, 13]

In [ ]:
[1,2,3,4,5,6,7,8,9,10,11,12,13][::2]

[1, 3, 5, 7, 9, 11, 13]

In [ ]:
[1,2,3,4,5,6,7,8,9,10,11,12,13][::5]

[1, 6, 11]